default_job = "clippy"

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = true

[jobs.test]
command = [
  "cargo",
  "test",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = true

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
